cDoctorAssistant/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from cDoctorAssistant import views

urlpatterns = [
                  url(r'^$', views.login_redirect, name='login_redirect'),
                  path('home/', include('patientbasicinfo.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('followup/', include('followup.urls')),
                  path('referralnotes/', include('referralnote.urls')),
                  path('history', include('history.urls')),
                  path('presentingfeatures/', include('presentingfeatures.urls')),
                  path('surgeryhormone', include('surgeryhormone.urls')),
                  url('radiotherapy/', include('radiotherapy.urls')),
                  url('chemotherapy/', include('chemotherapy.urls')),
                  url('targetedtherapy/', include('targetedtherapy.urls')),
                  url('tables/', include('tables.urls')),
                  url('analytics/', include('analytics.urls')),
                  url('pdfcreator/', include('pdfcreator.urls')),
                  path('admin/', admin.site.urls),
                  url('admin-login/$', admin.site.login, name='myadmin_login'),
                  url('^', include('django.contrib.auth.urls')),
                  url(r'^favicon.ico$',
                      RedirectView.as_view(  # the redirecting function
                          url=staticfiles_storage.url('img/favicon.ico'),
                          # converts the static directory + our favicon into a URL
                          # in my case, the result would be http://www.tumblingprogrammer.com/static/img/favicon.ico
                      ),
                      name="favicon"  # name of our view
                      ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patientbasicinfo/urls.py
from django.conf.urls import url
from django.urls import path, include

from patientbasicinfo import views, treatmentplan

app_name = 'pbi'
urlpatterns = [
    url(r'^$', views.ok, name='ok'),
    url(r'^new_patient/identity/$', views.new_identity, name='new_identity'),
    url(r'^(?P<p_id>[0-9]+)/edit_identity/$', views.edit_identity, name='edit_identity'),
    #
    url(r'^(?P<p_id>[0-9]+)/edit_comorbidity/$', views.edit_comorbidity, name='edit_comorbidity'),
    url(r'^(?P<p_id>[0-9]+)/new_comorbidity/$', views.new_comorbidity, name='new_comorbidity'),
    #
    url(r'^(?P<p_id>[0-9]+)/edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<p_id>[0-9]+)/new_profile/$', views.new_profile, name='new_profile'),
    #
    url(r'^uploadfile/(?P<p_id>[0-9]+)/$', views.upload_handler, name='upload_handler'),
    url(r'^delete_propic/(?P<p_id>[0-9]+)/$', views.delete_propic, name='delete_propic'),
    url(r'^change_propic/(?P<p_id>[0-9]+)/$', views.change_propic, name='change_propic'),
    #
    url(r'^(?P<p_id>[0-9]+)/new_treatmentplan/$', views.new_treatmentplan, name='new_treatmentplan'),
    url(r'^view_treatmentplan/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', treatmentplan.view_treatmentplan,
        name='view_treatmentplan'),
    url(r'^delete/treatmentplan/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/$', views.delete_treatmentplan,
        name='delete_treatmentplan'),
    #
    url(r'^(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/edit_prescription/$', views.edit_prescription, name='edit_prescription'),
    url(r'^(?P<p_id>[0-9]+)/new_prescription/$', views.new_prescription, name='new_prescription'),
    url(r'^delete/prescription/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/$', views.delete_prescription,
        name='delete_prescription'),
    #

]

pdfcreator/urls.py
from django.conf.urls import url

from pdfcreator import views, summary

app_name = 'pdfcreator'

urlpatterns = [
    url(r'^view/prescription/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/(?P<user_pk>[0-9]+)/$', views.view_prescription, name='view_prescription'),
    url(r'^pdf/prescription/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/$', views.print_prescription, name='print_prescription'),
    #
    url(r'^view/referralnote/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/(?P<user_pk>[0-9]+)/$',
        views.view_referralnote, name='view_referralnote'),
    url(r'^pdf/referralnote/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/$', views.print_referralnote,
        name='print_referralnote'),
    #
    url(r'^view/report/(?P<user_pk>[0-9]+)/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', summary.view_report, name='view_report'),
    url(r'^pdf/report/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', summary.print_report, name='print_report'),

]

tables/urls.py
from django.conf.urls import url

from tables import views, importDiseaseCode

app_name = 'table'

urlpatterns = [
    url(r'^edit_nactcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_nactcycle, name='edit_nactcycle'),
    url(r'^new_nactcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_nactcycle, name='new_nactcycle'),

    url(r'^edit_actcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_actcycle, name='edit_actcycle'),
    url(r'^new_actcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_actcycle, name='new_actcycle'),

    url(r'^edit_concurrcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_concurrcycle, name='edit_concurrcycle'),
    url(r'^new_concurrcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_concurrcycle, name='new_concurrcycle'),

    url(r'^edit_palliativecycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_palliativecycle, name='edit_palliativecycle'),
    url(r'^new_palliativecycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$',
        views.new_palliativecycle, name='new_palliativecycle'),
    # ---------------------------------------------------------------------------------------
    url(r'^edit_cobaltcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_cobaltcycle, name='edit_cobaltcycle'),
    url(r'^new_cobaltcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_cobaltcycle, name='new_cobaltcycle'),

    url(r'^edit_linaccycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_linaccycle, name='edit_linaccycle'),
    url(r'^new_linaccycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_linaccycle, name='new_linaccycle'),

    url(r'^edit_brachycycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_brachycycle, name='edit_brachycycle'),
    url(r'^new_brachycycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_brachycycle, name='new_brachycycle'),
    ####################
    # url(r'^import/$', importDiseaseCode.import_disease_code, name='import_disease_code')
]

patientbasicinfo/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

class Identity(models.Model):
    name = models.CharField(max_length=50)
    mobileNo = models.IntegerField(default=0, db_index=True)
    dateOfAdmission = models.DateField(default=now)
    email = models.EmailField(db_index=True, blank=True)
    unit = models.CharField(max_length=5, blank=True)
    religion = models.CharField(max_length=15, blank=True)
    gender = models.CharField(max_length=10, blank=True)
    dateOfBirth = models.DateField(blank=True)
    address = models.CharField(max_length=200, blank=True)
    referredBy = models.CharField(max_length=50, blank=True)
    regNo = models.CharField(max_length=6, blank=True)
    image = models.ImageField(upload_to='uploads/profile_pic/%Y/%m/%d/%H/%M/%S/', blank=True)

    def __str__(self):
        return self.name


class Comorbidity(models.Model):
    identity = models.ForeignKey(Identity, on_delete=models.CASCADE)
    hypertension = models.BooleanField(default=False)
    diabetes = models.BooleanField(default=False)
    cardiac = models.BooleanField(default=False)
    liver = models.BooleanField(default=False)
    kedney = models.BooleanField(default=False)
    others = models.BooleanField(default=False)

    # others = models.CharField(max_length=200)

    def __str__(self):
        return self.identity.name


class Profile(models.Model):
    identity = models.ForeignKey(Identity, on_delete=models.CASCADE)
    diseaseCode = models.CharField(max_length=50, blank=True)
    histopathology = models.CharField(max_length=50, blank=True)
    ihc = models.CharField(max_length=50, blank=True)
    er_pr = models.CharField(max_length=50, blank=True)
    stage = models.IntegerField(default=1, blank=True)
    tnm = models.CharField(max_length=50, blank=True)
    height = models.FloatField(max_length=5, blank=True)
    weight = models.FloatField(max_length=5, blank=True)
    bsa = models.FloatField(max_length=10, default=0, blank=True)  # need to fix  this... FloatField hobe!
    ps = models.CharField(max_length=10, blank=True)
    bloodGroup = models.CharField(max_length=3, blank=True)

    def __str__(self):
        return self.identity.name


class Medicine(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Dose(models.Model):
    dose = models.CharField(max_length=50)

    def __str__(self):
        return self.dose


class Timetable(models.Model):
    time = models.CharField(max_length=50)

    def __str__(self):
        return self.time


class Bangla(models.Model):
    bangla = models.CharField(max_length=50)

    def __str__(self):
        return self.bangla


class TreatmentPlan(models.Model):
    identity_fk = models.ForeignKey(Identity, on_delete=models.CASCADE)
    num = models.IntegerField()

    def __str__(self):
        return self.identity_fk.name+' '+str(self.num)


class Prescription(models.Model):
    identity_fk = models.ForeignKey(Identity, on_delete=models.CASCADE)
    date = models.DateField(default=now)
    num = models.IntegerField()
    details = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return self.identity_fk.name + ' ' + str(self.num)

patientbasicinfo/forms.py
from django import forms

from patientbasicinfo.models import Identity, Comorbidity, Profile, Prescription
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from tables.models import DiseaseCode


class DateInput(forms.DateInput):
    input_type = 'date'


class IdentityForm(forms.ModelForm):
    religion_choice = [
        ('Not Selected', 'Not Selected'), ('Islam', 'Islam'),
        ('Hindu', 'Hindu'), ('Christian', 'Christian'),
        ('Buddhist', 'Buddhist'), ('Others', 'Others')
    ]
    gender_choice = [
        ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')
    ]
    unit_choice = [
        ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')
    ]
    religion = forms.ChoiceField(widget=forms.Select, choices=religion_choice)
    gender = forms.ChoiceField(widget=forms.Select, choices=gender_choice)
    unit = forms.ChoiceField(widget=forms.Select, choices=unit_choice)

    class Meta:
        model = Identity
        fields = (
            'name', 'mobileNo', 'email', 'unit', 'gender', 'dateOfBirth', 'religion', 'address', 'referredBy', 'regNo'
        )
        widgets = {
            'dateOfBirth': DateInput()
        }


def get_my_choices():
    choice_list = DiseaseCode.objects.all()
    return choice_list


class ProfileForm(forms.ModelForm):
    bg_choice = [
        ('Not Selected', 'Not Selected'),
        ('O+', 'O+'), ('A+', 'A+'),
        ('B+', 'B+'), ('AB+', 'AB+'),
        ('O-', 'O-'), ('A-', 'A-'),
        ('B-', 'B-'), ('AB-', 'AB-'),

    ]

    bloodGroup = forms.ChoiceField(widget=forms.Select, choices=bg_choice)

    diseaseCode = forms.ModelChoiceField(widget=forms.Select, queryset=DiseaseCode.objects.all())

    '''def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['diseaseCode'] = forms.ChoiceField(
            choices=get_my_choices())
    '''
    class Meta:
        model = Profile
        # fields = "__all__"
        fields = (
            'diseaseCode', 'histopathology', 'ihc', 'er_pr', 'tnm', 'stage', 'height', 'weight', 'bsa', 'ps',
            'bloodGroup'
        )


class ComorbidityForm(forms.ModelForm):
    class Meta:
        model = Comorbidity
        fields = ('hypertension', 'diabetes', 'cardiac', 'liver', 'kedney', 'others')


class UploadForm(forms.ModelForm):
    class Meta:
        model = Identity
        fields = ('image',)


class PrescriptionForm(forms.ModelForm):
    class Meta:
        model = Prescription
        fields = ('details',)

patientbasicinfo/controller.py
from patientbasicinfo.models import Medicine, Dose, Timetable, Bangla


def autocomplete():
    bangla = []
    bangla_array = Bangla.objects.values_list('bangla', flat=True)
    for i in bangla_array:
        bangla.append(i)

    medicine = []
    medicine_array = Medicine.objects.values_list('name', flat=True)
    for i in medicine_array:
        medicine.append(i)

    dose = []
    dose_array = Dose.objects.values_list('dose', flat=True)
    for i in dose_array:
        dose.append(i)

    timetable = []
    timetable_array = Timetable.objects.values_list('time', flat=True)
    for i in timetable_array:
        timetable.append(i)
    context = {'bangla': bangla, 'medicine': medicine, 'dose': dose, 'timetable': timetable}
    return context

patientbasicinfo/templates/patientbasicinfo/ViewComorbidity.html
<div class="w3-container" style="margin-top:20px" id="comorbidity">
    {% if comorbidity %}
    <div class="w3-row-padding">
        <div class="w3-half w3-margin-bottom">
            <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">Comorbidity</li>
                    <li class="w3-padding-16">Hypertension</li>
                    <li class="w3-padding-16">Diabetes</li>
                    <li class="w3-padding-16">Cardiac</li>
                    <li class="w3-padding-16">Liver</li>
                    <li class="w3-padding-16">Kedney</li>
                    <li class="w3-padding-16">Others</li>
            </ul>
        </div>
         <div class="w3-half w3-margin-bottom">
             <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">#</li>
                    <li class="w3-padding-16"> {{comorbidity.hypertension}}</li>
                    <li class="w3-padding-16">{{comorbidity.diabetes}}</li>
                    <li class="w3-padding-16">{{comorbidity.cardiac}}</li>
                    <li class="w3-padding-16">{{comorbidity.liver}}</li>
                    <li class="w3-padding-16">{{comorbidity.kedney}}</li>
                    <li class="w3-padding-16">{{comorbidity.others}}</li>
             </ul>
        </div>
        <br><a href="{% url 'pbi:edit_comorbidity' comorbidity.identity.pk %}" class="w3-btn w3-green">Edit Comorbidity</a><br>


    {% else %}
    <ul><h2>No data in Comorbidity</h2>
        <a href="{% url 'pbi:new_comorbidity' patient.pk %}" class="w3-btn w3-green">New Comorbidity</a>
    </ul>
    </ul>
    {% endif %}

</div>

patientbasicinfo/templates/patientbasicinfo/ViewIdentity.html
{% load staticfiles %}
<div class="w3-container" id="identity">
<div class="w3-container w3-black">

    <h2 align="center">Identity</h2>

</div>

    <div class="w3-half w3-margin-bottom">
        <ul>
    <p>Name   : {{patient.name}}</p>
    <p>ID   : {{patient.pk}}</p>
    <p>Mobile : {{patient.mobileNo}}</p>
            <p>Email : {{patient.email}}</p>
    <p>unit   : {{patient.unit}}</p>
    <p>gender : {{patient.gender}}</p>
    <p>Address: {{patient.address}}</p>
    <p>Date Of Admission: {{patient.dateOfAdmission}}</p>
    <p>Referred By: {{patient.referredBy}}</p>
    <a href="{% url 'pbi:edit_identity' patient.pk %}" class="w3-btn w3-green">Edit Identity</a>
</ul>
    </div>
    <div class="w3-half">
{% if patient.image %}
    <p>
        <img src="{{ patient.image.url }}" width="240" height="240" alt="No Image Available">
        <br>
        <a href="{% url 'pbi:change_propic' patient.pk %}" class="w3-btn w3-green">Change Photo</a>
        <a href="{% url 'pbi:delete_propic' patient.pk %}" class="w3-btn w3-red"
      onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
    </p>
        {% else %}
    <p>
        <img src="{% static 'img/blank-profile-picture.png' %}" width="240" height="240" alt="No Image Available">
        <br>
        <a href="{% url 'pbi:upload_handler' patient.pk %}" class="w3-btn w3-green">Upload Picture</a>
    </p>
{% endif %}
    </div>


</div>

patientbasicinfo/templates/patientbasicinfo/ViewPrescription.html
<div class="w3-container" style="margin-top:20px">
    {% if prescription %}
    {% for i in prescription %}
<div class="w3-row-padding">
        <div class="w3-half w3-margin-bottom">
            <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">Prescription</li>
                <li class="w3-padding-16">Date</li>
                <li class="w3-padding-16">Details</li>
            </ul>
        </div>
         <div class="w3-half w3-margin-bottom">
             <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">#{{i.num}}</li>
                 <li class="w3-padding-16">{{i.date}}</li>
                 <li class="w3-padding-16">{{i.details}}</li>
             </ul>
        </div>
</div>
    <br><a href="{% url 'pbi:edit_prescription' i.identity_fk.pk i.num %}" class="w3-btn w3-green">Edit</a>
    <a href="{% url 'pdfcreator:view_prescription' i.identity_fk.pk i.num user.pk %}" class="w3-btn w3-blue">Print</a>

    <a href="{% url 'pbi:delete_prescription' i.identity_fk.pk i.num %}" class="w3-btn w3-red w3-right"
    onclick="return confirm('Are you sure you want to delete this?')">Delete</a>

<br>
{% endfor %}
<div class = "w3-container">
    <p>
    <a href="{% url 'pbi:new_prescription' patient.pk %}" class="w3-btn w3-green">New Prescription</a></p>
</div>

{% else %}
<ul>
    <h3> No Prescription Yet! </h3>
    <a href="{% url 'pbi:new_prescription' patient.pk %}" class="w3-btn w3-green">New Prescription</a>
</ul>
{% endif %}
</div>

patientbasicinfo/templates/patientbasicinfo/ViewProfile.html
<div class="w3-container" style="margin-top:20px" id="profile">
{% if profile %}
    <div class="w3-row-padding">
        <div class="w3-half w3-margin-bottom">
            <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">Profile</li>
                    <li class="w3-padding-16">Disease Code</li>
                    <li class="w3-padding-16">Histopathology</li>
                    <li class="w3-padding-16">IHC</li>
                    <li class="w3-padding-16">ER/PR</li>
                    <li class="w3-padding-16">TNM</li>
                    <li class="w3-padding-16">Stage</li>
            <li class="w3-padding-16">Height</li>
            <li class="w3-padding-16">Weight</li>
            <li class="w3-padding-16">BSA</li>
            <li class="w3-padding-16">PS</li>
            <li class="w3-padding-16">Blood Group</li>
            </ul>
        </div>
         <div class="w3-half w3-margin-bottom">
             <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">#</li>
                    <li class="w3-padding-16"> {{profile.diseaseCode}}</li>
                    <li class="w3-padding-16">{{profile.histopathology}}</li>
                    <li class="w3-padding-16">{{profile.ihc}}</li>
                    <li class="w3-padding-16">{{profile.er_pr}}</li>
                    <li class="w3-padding-16">{{profile.tnm}}</li>
                    <li class="w3-padding-16">{{profile.stage}}</li>
            <li class="w3-padding-16">{{profile.height}}</li>
            <li class="w3-padding-16">{{profile.weight}}</li>
            <li class="w3-padding-16">{{profile.bsa}}</li>
            <li class="w3-padding-16">{{profile.ps}}</li>
            <li class="w3-padding-16">{{profile.bloodGroup}}</li>
             </ul>
        </div>
    <br>
         <a href="{% url 'pbi:edit_profile' profile.identity.pk %}" class="w3-btn w3-green">Edit Profile</a>
    <br>
    </div>

{% else %}
    <ul><h2>Nothing to show in Profile</h2>
    <a href="{% url 'pbi:new_profile' patient.pk %}" class="w3-btn w3-green">New Profile</a>
    </ul>
{% endif %}

</div>

patientbasicinfo/templates/patientbasicinfo/dummy.html
<form method = post  enctype="multipart/form-data">
        <script type="text/javascript">


function SelectElement(valueToSelect)
{
    var element = document.getElementById('id_religion');
    element.value = valueToSelect;
}


        </script>
<script type="text/javascript">
    $(function(){
    var my_date = {{identity.dateOfBirth | safe }};
    var my_religion = {{ identity.religion | safe }};
    SelectElement(my_religion);
    document.getElementById("id_dateOfBirth").valueAsDate = my_date;
    });
</script>
        {% csrf_token %}
<p><label for="id_name">Name:</label>
    <input type="text" name="name" maxlength="50" value="{{identity.name}}" required id="id_name" />
</p>
<p><label for="id_mobileNo">MobileNo:</label>
    <input type="number" name="mobileNo" required id="id_mobileNo" value="{{identity.mobileNo}}" /></p>
<p><label for="id_unit">Unit:</label> <input type="text" name="unit" maxlength="5" id="id_unit" /></p>
<p><label for="id_gender">Gender:</label> <input type="text" name="gender" maxlength="10" id="id_gender" /></p>
<p><label for="id_religion">Religion:</label><select name="religion" required id="id_religion">
    <option value="Islam">Islam</option>
    <option value="Hindu">Hindu</option>
    <option value="Buddhist">Buddhist</option>
    <option value="Christian">Christian</option>
    <option value="Others">Others</option>
    </select>
</p>
<p><label for="id_dateOfBirth">DateOfBirth:</label>
    <input type="date" name="dateOfBirth" value="{{identity.dateOfBirth}}" required id="id_dateOfBirth" />
    <!--input type="hidden" name="initial-dateOfBirth" value="&lt;django.db.models.query_utils.DeferredAttribute object at 0x7f77a8f11630&gt;" id="initial-id_dateOfBirth" /-->
</p>
<p>
<label for="id_address">Address:</label>
    <input type="text" name="address" maxlength="200" id="id_address" value="{{identity.address}}"/>
</p>
<p><label for="id_referredBy">RefferedBy:</label>
    <input type="text" name="referredBy" maxlength="50" id="id_referredBy" value="{{identity.referredBy}}"/>
</p>
<p><label for="id_regNo">RegNo:</label>
    <input type="text" name="regNo" maxlength="6" value="{{identity.regNo}}"  id="id_regNo" />
</p>
        <button type = "submit" style="color:#047ff8;">Submit</button>
        <button type="reset" value="Reset">Reset</button>
    </form>
<!--
****************************************************************
-->
<form method = post  enctype="multipart/form-data">
        {% csrf_token %}
<p><label for="id_name">Name:</label> <input type="text" name="name" value="{{identity.name}}" maxlength="50" required id="id_name" /></p>
<p><label for="id_mobileNo">MobileNo:</label> <input type="number" name="mobileNo" value="{{identity.mobileNo}}" required id="id_mobileNo" /></p>
<p><label for="id_unit">Unit:</label> <input type="text" name="unit" value="{{identity.unit}}" maxlength="5" required id="id_unit"
list="typeUnit"/></p>
<datalist id="typeUnit">
    <option value="A">A</option>
    <option value="B">B</option>
    <option value="C">C</option>
    <option value="D">D</option>
    <option value="E">E</option>
</datalist>
<p><label for="id_gender">Gender:</label> <input type="text" name="gender" value="{{identity.gender}}" maxlength="10" required id="id_gender"
list="typeGender"/></p>
        <datalist id="typeGender">
    <option value="Male">Male</option>
    <option value="Female">Female</option>
    <option value="Others">Others</option>
</datalist>
<p><label for="id_religion">Religion:</label><select name="religion" required id="id_religion">
    <option value="Islam">Islam</option>
    <option value="Hindu">Hindu</option>
    <option value="Buddhist">Buddhist</option>
    <option value="Christian">Christian</option>
    <option value="Others">Others</option>
    </select>
</p>
<!--p><label for="id_religion">Religion:</label> <input type="text" name="religion" value="{{identity.religion}}" maxlength="5" required id="id_religion"
list="typeReligion"/></p>
<datalist id="typeReligion">
            <option value="Islam">Islam</option>
    <option value="Hindu">Hindu</option>
    <option value="Buddhist">Buddhist</option>
    <option value="Christian">Christian</option>
    <option value="Others">Others</option>
</datalist-->


        <p><label for="id_dateOfBirth">DateOfBirth:</label> <input type="date" name="dateOfBirth" value="{{identity.dateOfBirth}}" required id="id_dateOfBirth" />
    <!--input type="hidden" name="initial-dateOfBirth" value="&lt;django.db.models.query_utils.DeferredAttribute object at 0x7f77a8f11630&gt;" id="initial-id_dateOfBirth" /-->
</p>
<p><label for="id_address">Address:</label> <input type="text" name="address" value="{{identity.address}}" maxlength="200" required id="id_address" /></p>
<p><label for="id_refferedBy">RefferedBy:</label> <input type="text" name="refferedBy" value="{{identity.refferedBy}}" maxlength="50" required id="id_refferedBy" /></p>
<p><label for="id_regNo">RegNo:</label> <input type="number" name="regNo" value="{{identity.regNo}}" required id="id_regNo" /></p>
<!--p><label for="id_image">Image:</label> <input type="file" name="image" id="id_image" /></p-->
        <button type = "submit" style="color:#047ff8;">Submit</button>
        <button type="reset" value="Reset">Reset</button>
    </form>