cDoctorAssistant/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from cDoctorAssistant import views

urlpatterns = [
                  url(r'^$', views.login_redirect, name='login_redirect'),
                  path('home/', include('patientbasicinfo.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('followup/', include('followup.urls')),
                  path('referralnotes/', include('referralnote.urls')),
                  path('history', include('history.urls')),
                  path('presentingfeatures/', include('presentingfeatures.urls')),
                  path('surgeryhormone', include('surgeryhormone.urls')),
                  url('radiotherapy/', include('radiotherapy.urls')),
                  url('chemotherapy/', include('chemotherapy.urls')),
                  url('targetedtherapy/', include('targetedtherapy.urls')),
                  url('tables/', include('tables.urls')),
                  url('analytics/', include('analytics.urls')),
                  url('pdfcreator/', include('pdfcreator.urls')),
                  path('admin/', admin.site.urls),
                  url('admin-login/$', admin.site.login, name='myadmin_login'),
                  url('^', include('django.contrib.auth.urls')),
                  url(r'^favicon.ico$',
                      RedirectView.as_view(  # the redirecting function
                          url=staticfiles_storage.url('img/favicon.ico'),
                          # converts the static directory + our favicon into a URL
                          # in my case, the result would be http://www.tumblingprogrammer.com/static/img/favicon.ico
                      ),
                      name="favicon"  # name of our view
                      ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

radiotherapy/urls.py
from django.conf.urls import url

from radiotherapy import views

app_name = 'radiotherapy'



urlpatterns = [
    url(r'^Treatment_plan/RadioTherapy/Cobalt/new/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_Cobalt, name='new_Cobalt'),
    url(r'^Treatment_plan/RadioTherapy/Cobalt/edit/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.edit_Cobalt, name='edit_Cobalt'),

    url(r'^Treatment_plan/RadioTherapy/Linac/new/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_Linac, name='new_Linac'),
    url(r'^Treatment_plan/RadioTherapy/Linac/edit/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.edit_Linac, name='edit_Linac'),

    url(r'^Treatment_plan/RadioTherapy/Brachy/new/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_Brachy, name='new_Brachy'),
    url(r'^Treatment_plan/RadioTherapy/Brachy/edit/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.edit_Brachy, name='edit_Brachy'),
]

tables/urls.py
from django.conf.urls import url

from tables import views, importDiseaseCode

app_name = 'table'

urlpatterns = [
    url(r'^edit_nactcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_nactcycle, name='edit_nactcycle'),
    url(r'^new_nactcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_nactcycle, name='new_nactcycle'),

    url(r'^edit_actcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_actcycle, name='edit_actcycle'),
    url(r'^new_actcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_actcycle, name='new_actcycle'),

    url(r'^edit_concurrcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_concurrcycle, name='edit_concurrcycle'),
    url(r'^new_concurrcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_concurrcycle, name='new_concurrcycle'),

    url(r'^edit_palliativecycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_palliativecycle, name='edit_palliativecycle'),
    url(r'^new_palliativecycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$',
        views.new_palliativecycle, name='new_palliativecycle'),
    # ---------------------------------------------------------------------------------------
    url(r'^edit_cobaltcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_cobaltcycle, name='edit_cobaltcycle'),
    url(r'^new_cobaltcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_cobaltcycle, name='new_cobaltcycle'),

    url(r'^edit_linaccycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_linaccycle, name='edit_linaccycle'),
    url(r'^new_linaccycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_linaccycle, name='new_linaccycle'),

    url(r'^edit_brachycycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_brachycycle, name='edit_brachycycle'),
    url(r'^new_brachycycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_brachycycle, name='new_brachycycle'),
    ####################
    # url(r'^import/$', importDiseaseCode.import_disease_code, name='import_disease_code')
]

radiotherapy/models.py
from django.db import models
# Create your models here.
from django.utils.timezone import now

from patientbasicinfo.models import TreatmentPlan


class RadioTherapy(models.Model):
    tp_fk = models.ForeignKey(TreatmentPlan, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, db_index=True)
    intensity = models.CharField(max_length=50, blank=True)
    dose = models.CharField(max_length=50, blank=True)
    gray = models.FloatField(default=0, blank=True)
    fractionFx = models.FloatField(default=0, blank=True)
    startDate = models.DateField(default=now, blank=True)
    endDate = models.DateField(default=now, blank=True)
    #details = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.identity.name+' - '+self.type

radiotherapy/forms.py
from django import forms

from radiotherapy.models import RadioTherapy


class DateInput(forms.DateInput):
    input_type = 'date'


class RadioTherapyForm(forms.ModelForm):
    class Meta:
        model = RadioTherapy
        fields = (
             'intensity','dose',
             'gray', 'fractionFx', 'startDate', 'endDate')  # ekhan theke 'type' soray disi.
        widgets = {
            'startDate': DateInput(),
            'endDate' : DateInput()
        }

radiotherapy/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from patientbasicinfo.controller import autocomplete
from patientbasicinfo.models import TreatmentPlan
from radiotherapy.forms import RadioTherapyForm
from radiotherapy.models import RadioTherapy


@login_required
def new_Cobalt(request, p_id, tp_num):
    if request.method == "POST":
        form = RadioTherapyForm(request.POST)
        if form.is_valid():
            cobalt = form.save(commit=False)
            tmp_tp_fk = TreatmentPlan.objects.get(identity_fk=p_id, num=tp_num)
            cobalt.tp_fk = tmp_tp_fk
            cobalt.type = "Cobalt"
            cobalt.save()
        return redirect('pbi:view_treatmentplan', p_id=p_id, tp_num=tp_num)
    else:
        form = RadioTherapyForm()
    ac = autocomplete()
    z = {'form': form, 'type': 'Cobalt'}
    context = {**z, **ac}
    return render(request, 'radiotherapy/EditRadioTherapy.html', context)


@login_required
def edit_Cobalt(request, p_id, tp_num):
    tmp_tp_fk = TreatmentPlan.objects.get(identity_fk=p_id, num=tp_num)
    if not RadioTherapy.objects.filter(tp_fk=tmp_tp_fk, type="Cobalt").exists():
        return new_Cobalt(request, p_id, tp_num)
    else:
        p_radiotherapy = get_object_or_404(RadioTherapy, tp_fk=tmp_tp_fk, type="Cobalt")
        if request.method == "POST":
            form = RadioTherapyForm(request.POST, instance=p_radiotherapy)
            if form.is_valid():
                p_radiotherapy = form.save()  # """ ekhane change kora lagte pare"""
                return redirect('pbi:view_treatmentplan', p_id=p_id, tp_num=tp_num)
        else:
            form = RadioTherapyForm(instance=p_radiotherapy)
        ac = autocomplete()
        z = {'form': form, 'p_radiotherapy': p_radiotherapy, 'type': 'Cobalt'}
        context = {**z, **ac}
        return render(request, 'radiotherapy/EditRadioTherapy.html', context)


@login_required
def new_Linac(request, p_id, tp_num):
    if request.method == "POST":
        form = RadioTherapyForm(request.POST)
        if form.is_valid():
            linac = form.save(commit=False)
            tmp_tp_fk = TreatmentPlan.objects.get(identity_fk=p_id, num=tp_num)
            linac.tp_fk = tmp_tp_fk
            linac.type = "Linac"
            linac.save()
        return redirect('pbi:view_treatmentplan', p_id=p_id, tp_num=tp_num)
    else:
        form = RadioTherapyForm()
    ac = autocomplete()
    z = {'form': form, 'type': 'Linac'}
    context = {**z, **ac}
    return render(request, 'radiotherapy/EditRadioTherapy.html', context)


@login_required
def edit_Linac(request, p_id, tp_num):
    tmp_tp_fk = TreatmentPlan.objects.get(identity_fk=p_id, num=tp_num)
    if not RadioTherapy.objects.filter(tp_fk=tmp_tp_fk, type="Linac").exists():
        return new_Linac(request, p_id, tp_num)
    else:
        p_radiotherapy = get_object_or_404(RadioTherapy, tp_fk=tmp_tp_fk, type="Linac")
        if request.method == "POST":
            form = RadioTherapyForm(request.POST, instance=p_radiotherapy)
            if form.is_valid():
                p_radiotherapy = form.save()  # """ ekhane change kora lagte pare"""
                return redirect('pbi:view_treatmentplan', p_id=p_id, tp_num=tp_num)
        else:
            form = RadioTherapyForm(instance=p_radiotherapy)
        ac = autocomplete()
        z = {'form': form, 'p_radiotherapy': p_radiotherapy, 'type': 'Linac'}
        context = {**z, **ac}
        return render(request, 'radiotherapy/EditRadioTherapy.html', context)


@login_required
def new_Brachy(request, p_id, tp_num):
    if request.method == "POST":
        form = RadioTherapyForm(request.POST)
        if form.is_valid():
            brachy = form.save(commit=False)
            tmp_tp_fk = TreatmentPlan.objects.get(identity_fk=p_id, num=tp_num)
            brachy.tp_fk = tmp_tp_fk
            brachy.type = "Brachy"
            brachy.save()
        return redirect('pbi:view_treatmentplan', p_id=p_id, tp_num=tp_num)
    else:
        form = RadioTherapyForm()
    ac = autocomplete()
    z = {'form': form, 'type': 'Brachy'}
    context = {**z, **ac}
    return render(request, 'radiotherapy/EditRadioTherapy.html', context)


@login_required
def edit_Brachy(request, p_id, tp_num):
    tmp_tp_fk = TreatmentPlan.objects.get(identity_fk=p_id, num=tp_num)
    if not RadioTherapy.objects.filter(tp_fk=tmp_tp_fk, type="Brachy").exists():
        return new_Brachy(request, p_id, tp_num)
    else:
        p_radiotherapy = get_object_or_404(RadioTherapy, tp_fk=tmp_tp_fk, type="Brachy")
        if request.method == "POST":
            form = RadioTherapyForm(request.POST, instance=p_radiotherapy)
            if form.is_valid():
                p_radiotherapy = form.save()  # """ ekhane change kora lagte pare"""
                return redirect('pbi:view_treatmentplan', p_id=p_id, tp_num=tp_num)
        else:
            form = RadioTherapyForm(instance=p_radiotherapy)
        ac = autocomplete()
        z = {'form': form, 'p_radiotherapy': p_radiotherapy, 'type': 'Brachy'}
        context = {**z, **ac}
        return render(request, 'radiotherapy/EditRadioTherapy.html', context)

radiotherapy/templates/radiotherapy/Brachy.html
<div class="w3-container" style="margin-top:20px" id="brachy">
    {% if brachy %}
<div class="w3-row-padding">
        <div class="w3-half w3-margin-bottom">
            <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">Brachy Therapy</li>
                    <li class="w3-padding-16">Type</li>
                    <li class="w3-padding-16">Intensity</li>
                    <li class="w3-padding-16">Dose</li>
                    <li class="w3-padding-16">Gray</li>
                    <li class="w3-padding-16">Fraction(Fx)</li>
                    <li class="w3-padding-16">Start Date</li>
                    <li class="w3-padding-16">End Date</li>
                    <!--li class="w3-padding-16">Details</li-->
            </ul>
        </div>
         <div class="w3-half w3-margin-bottom">
             <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">#</li>
                    <li class="w3-padding-16">{{brachy.type}}</li>
                    <li class="w3-padding-16">{{brachy.intensity}}</li>
                    <li class="w3-padding-16">{{brachy.dose}} </li>
                    <li class="w3-padding-16">{{brachy.gray}} </li>
                    <li class="w3-padding-16">{{brachy.fractionFx}}</li>
                    <li class="w3-padding-16">{{brachy.startDate}}</li>
                    <li class="w3-padding-16">{{brachy.endDate}}</li>
                    <!--li class="w3-padding-16">{{cobalt.details}}</li-->
             </ul>
        </div>
</div>
    <br><a href="{% url 'radiotherapy:edit_Brachy' patient.pk tp_fk.num %}"
    class="w3-btn w3-green">Edit Brachy Therapy</a>
<br>



{% else %}
<ul>
    <h3> Nothing in Brachy Therapy </h3>
    <a href="{% url 'radiotherapy:new_Brachy' patient.pk tp_fk.num %}" class="w3-btn w3-green">New Brachy Therapy</a>
</ul>
{% endif %}
</div>

radiotherapy/templates/radiotherapy/Cobalt.html
<div class="w3-container" style="margin-top:20px" id="cobalt">
    {% if cobalt %}
<div class="w3-row-padding">
        <div class="w3-half w3-margin-bottom">
            <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">Tele-Therapy/Cobalt</li>
                    <li class="w3-padding-16">Type</li>
                    <li class="w3-padding-16">Intensity</li>
                    <li class="w3-padding-16">Dose</li>
                    <li class="w3-padding-16">Gray</li>
                    <li class="w3-padding-16">Fraction(Fx)</li>
                    <li class="w3-padding-16">Start Date</li>
                    <li class="w3-padding-16">End Date</li>
                    <!--li class="w3-padding-16">Details</li-->
            </ul>
        </div>
         <div class="w3-half w3-margin-bottom">
             <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">#</li>
                    <li class="w3-padding-16">{{cobalt.type}}</li>
                    <li class="w3-padding-16">{{cobalt.intensity}}</li>
                    <li class="w3-padding-16">{{cobalt.dose}} </li>
                    <li class="w3-padding-16">{{cobalt.gray}} </li>
                    <li class="w3-padding-16">{{cobalt.fractionFx}}</li>
                    <li class="w3-padding-16">{{cobalt.startDate}}</li>
                    <li class="w3-padding-16">{{cobalt.endDate}}</li>
                    <!--li class="w3-padding-16">{{cobalt.details}}</li-->
             </ul>
        </div>
</div>
    <br><a href="{% url 'radiotherapy:edit_Cobalt' patient.pk tp_fk.num %}"
    class="w3-btn w3-green">Edit Cobalt Therapy</a>
<br>



{% else %}
<ul>
    <h3> Nothing in Cobalt Therapy </h3>
    <a href="{% url 'radiotherapy:new_Cobalt' patient.pk tp_fk.num %}" class="w3-btn w3-green">New Cobalt Therapy</a>
</ul>
{% endif %}
</div>

radiotherapy/templates/radiotherapy/EditRadioTherapy.html
{% extends 'accounts/base.html' %}
{% block body %}
{% load staticfiles %}

<!--{#% if not medicine %}
<script type="text/javascript" src="{% static 'js/autocomplete.js' %}"></script>
{#% endif %}-->
<div class="w3-display-middle w3-mobile">
<ul>
<h1>RadioTherapy</h1>
    <h3>{{type}}</h3>
    <form method = post>
        {% csrf_token %}
        {{form.as_p}}
<!--p><label for="id_intensity">Intensity:</label>
    <input type="text" name="intensity" maxlength="50" id="id_intensity" value="{{p_radiotherapy.intensity}}" /></p>
<p><label for="id_dose">Dose:</label>
    <input type="text" name="dose" maxlength="50" id="id_dose" value="{{p_radiotherapy.dose}}" /></p>
<p><label for="id_gray">Gray:</label>
    <input type="number" name="gray" step="any" id="id_gray" value="{{p_radiotherapy.gray}}" /></p>
<p><label for="id_fractionFx">FractionFx:</label>
    <input type="number" name="fractionFx" value="{{p_radiotherapy.fractionFx}}" step="any" id="id_fractionFx" /></p>
<p><label for="id_startDate">StartDate:</label> <input type="date" name="startDate" value="{{p_radiotherapy.startDate}}"
    id="id_startDate" /><input type="hidden" name="initial-startDate" value="{{p_radiotherapy.startDate}}"
                               id="initial-id_startDate" /></p>
<p><label for="id_endDate">EndDate:</label>
    <input type="date" name="endDate" value="{{p_radiotherapy.endDate}}" id="id_endDate" />
    <input type="hidden" name="initial-endDate" value="{{p_radiotherapy.endDate}}" id="initial-id_endDate" /></p>

<p><label for="id_details">Details:</label>
    <textarea id="inputor" class="inputor" name="details" maxlength="200"
               id="id_details">{{p_radiotherapy.details}}</textarea></p-->
        <button type = "submit" style="color:#047ff8;">Submit</button>
        <button type="reset" value="Reset">Reset</button>
    </form>
</ul>
    </div>
{% endblock %}

radiotherapy/templates/radiotherapy/Linac.html
<div class="w3-container" style="margin-top:20px" id="linac">
    {% if linac %}
<div class="w3-row-padding">
        <div class="w3-half w3-margin-bottom">
            <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">Tele-Therapy/Linac</li>
                    <li class="w3-padding-16">Type</li>
                    <li class="w3-padding-16">Intensity</li>
                    <li class="w3-padding-16">Dose</li>
                    <li class="w3-padding-16">Gray</li>
                    <li class="w3-padding-16">Fraction(Fx)</li>
                    <li class="w3-padding-16">Start Date</li>
                    <li class="w3-padding-16">End Date</li>
                    <!--li class="w3-padding-16">Details</li-->
            </ul>
        </div>
         <div class="w3-half w3-margin-bottom">
             <ul class="w3-ul w3-light-gray w3-center">
            <li class="w3-black w3-xlarge w3-padding-16">#</li>
                    <li class="w3-padding-16">{{linac.type}}</li>
                    <li class="w3-padding-16">{{linac.intensity}}</li>
                    <li class="w3-padding-16">{{linac.dose}} </li>
                    <li class="w3-padding-16">{{linac.gray}} </li>
                    <li class="w3-padding-16">{{linac.fractionFx}}</li>
                    <li class="w3-padding-16">{{linac.startDate}}</li>
                    <li class="w3-padding-16">{{linac.endDate}}</li>
                    <!--li class="w3-padding-16">{{cobalt.details}}</li-->
             </ul>
        </div>
</div>
    <br><a href="{% url 'radiotherapy:edit_Linac' patient.pk tp_fk.num %}"
    class="w3-btn w3-green">Edit Linac Therapy</a>
<br>



{% else %}
<ul>
    <h3> Nothing in Linac Therapy </h3>
    <a href="{% url 'radiotherapy:new_Linac' patient.pk tp_fk.num %}" class="w3-btn w3-green">New Linac Therapy</a>
</ul>
{% endif %}
</div>

radiotherapy/templates/radiotherapy/ViewRadioTherapy.html
<div class="w3-container" id="radiotherapy">
<div class="w3-container w3-white">

    <h2 align="center">Radio-Therapy</h2>

</div>
    {%include 'radiotherapy/Cobalt.html' %}
   <div class="w3-container">
        <div></div>
    </div>

        {%include 'tables/cobalt_chart.html' %}
   <div class="w3-container">
        <div></div>
    </div>

<!--
    -->
{%include 'radiotherapy/Linac.html' %}
<div class="w3-container">
        <div></div>
    </div>

            {%include 'tables/linac_chart.html' %}
   <div class="w3-container">
        <div></div>
    </div>


    {%include 'radiotherapy/Brachy.html' %}
<div class="w3-container">
        <div></div>
    </div>
                {%include 'tables/brachy_chart.html' %}
   <div class="w3-container">
        <div></div>
    </div>



</div>