accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path, include

from accounts import views

# app_name = 'accounts'
from accounts.patientdetails import view_patientdetails

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='mylogin'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='mylogout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/change_password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\]+)/(?P<token>[0-9A-Za-z]{1,13}[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete'),
    url(r'^(?P<p_id>[0-9]+)/view_patientdetails/$', view_patientdetails, name='view_patientdetails'),
    # url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(P?<token>.+)$', password_reset_confirm,
    #    name='password_reset_confirm'),

    url(r'^doctorinfo/$', views.view_doctorinfo, name='view_doctorinfo'),
    url(r'^doctorinfo/edit/$', views.edit_doctorinfo, name='edit_doctorinfo'),
    url(r'^doctorinfo/new/$', views.new_doctorinfo, name='new_doctorinfo'),

]

analytics/urls.py
from django.conf.urls import url

from analytics import views

app_name = 'analytics'

urlpatterns = [
    url(r'^result/form_handle/$', views.form_handle, name='form_handle'),
    url(r'^result/form_handle_pk/$', views.form_handle_pk, name='form_handle_pk'),
    url(r'^result/form_handle_date/$', views.form_handle_date, name='form_handle_date'),

    url(r'^result/stage_one_query/$', views.stage_one, name='sq_stage_one'),
    url(r'^result/stage_two_query/$', views.stage_two, name='sq_stage_two'),
    url(r'^result/stage_three_query/$', views.stage_three, name='sq_stage_three'),
    url(r'^result/stage_four_query/$', views.stage_four, name='sq_stage_four'),
    url(r'^result/linac/$',views.linac,name='sq_linac'),
    url(r'^result/cobalt/$',views.cobalt,name='sq_cobalt'),
    url(r'^result/brachy/$',views.brachy,name='sq_brachy'),
    url(r'^result/nact/$', views.nact, name='sq_nact'),
    url(r'^result/act/$', views.act, name='sq_act'),
    url(r'^result/concurrent/$', views.concurrent, name='sq_concurrent'),
    url(r'^result/palliative/$', views.palliative, name='sq_palliative'),

    url(r'^calculator/$', views.calculators, name='calculators'),

]

cDoctorAssistant/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from cDoctorAssistant import views

urlpatterns = [
                  url(r'^$', views.login_redirect, name='login_redirect'),
                  path('home/', include('patientbasicinfo.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('followup/', include('followup.urls')),
                  path('referralnotes/', include('referralnote.urls')),
                  path('history', include('history.urls')),
                  path('presentingfeatures/', include('presentingfeatures.urls')),
                  path('surgeryhormone', include('surgeryhormone.urls')),
                  url('radiotherapy/', include('radiotherapy.urls')),
                  url('chemotherapy/', include('chemotherapy.urls')),
                  url('targetedtherapy/', include('targetedtherapy.urls')),
                  url('tables/', include('tables.urls')),
                  url('analytics/', include('analytics.urls')),
                  url('pdfcreator/', include('pdfcreator.urls')),
                  path('admin/', admin.site.urls),
                  url('admin-login/$', admin.site.login, name='myadmin_login'),
                  url('^', include('django.contrib.auth.urls')),
                  url(r'^favicon.ico$',
                      RedirectView.as_view(  # the redirecting function
                          url=staticfiles_storage.url('img/favicon.ico'),
                          # converts the static directory + our favicon into a URL
                          # in my case, the result would be http://www.tumblingprogrammer.com/static/img/favicon.ico
                      ),
                      name="favicon"  # name of our view
                      ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patientbasicinfo/urls.py
from django.conf.urls import url
from django.urls import path, include

from patientbasicinfo import views, treatmentplan

app_name = 'pbi'
urlpatterns = [
    url(r'^$', views.ok, name='ok'),
    url(r'^new_patient/identity/$', views.new_identity, name='new_identity'),
    url(r'^(?P<p_id>[0-9]+)/edit_identity/$', views.edit_identity, name='edit_identity'),
    #
    url(r'^(?P<p_id>[0-9]+)/edit_comorbidity/$', views.edit_comorbidity, name='edit_comorbidity'),
    url(r'^(?P<p_id>[0-9]+)/new_comorbidity/$', views.new_comorbidity, name='new_comorbidity'),
    #
    url(r'^(?P<p_id>[0-9]+)/edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<p_id>[0-9]+)/new_profile/$', views.new_profile, name='new_profile'),
    #
    url(r'^uploadfile/(?P<p_id>[0-9]+)/$', views.upload_handler, name='upload_handler'),
    url(r'^delete_propic/(?P<p_id>[0-9]+)/$', views.delete_propic, name='delete_propic'),
    url(r'^change_propic/(?P<p_id>[0-9]+)/$', views.change_propic, name='change_propic'),
    #
    url(r'^(?P<p_id>[0-9]+)/new_treatmentplan/$', views.new_treatmentplan, name='new_treatmentplan'),
    url(r'^view_treatmentplan/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', treatmentplan.view_treatmentplan,
        name='view_treatmentplan'),
    url(r'^delete/treatmentplan/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/$', views.delete_treatmentplan,
        name='delete_treatmentplan'),
    #
    url(r'^(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/edit_prescription/$', views.edit_prescription, name='edit_prescription'),
    url(r'^(?P<p_id>[0-9]+)/new_prescription/$', views.new_prescription, name='new_prescription'),
    url(r'^delete/prescription/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/$', views.delete_prescription,
        name='delete_prescription'),
    #

]

tables/urls.py
from django.conf.urls import url

from tables import views, importDiseaseCode

app_name = 'table'

urlpatterns = [
    url(r'^edit_nactcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_nactcycle, name='edit_nactcycle'),
    url(r'^new_nactcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_nactcycle, name='new_nactcycle'),

    url(r'^edit_actcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_actcycle, name='edit_actcycle'),
    url(r'^new_actcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_actcycle, name='new_actcycle'),

    url(r'^edit_concurrcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_concurrcycle, name='edit_concurrcycle'),
    url(r'^new_concurrcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_concurrcycle, name='new_concurrcycle'),

    url(r'^edit_palliativecycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_palliativecycle, name='edit_palliativecycle'),
    url(r'^new_palliativecycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$',
        views.new_palliativecycle, name='new_palliativecycle'),
    # ---------------------------------------------------------------------------------------
    url(r'^edit_cobaltcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_cobaltcycle, name='edit_cobaltcycle'),
    url(r'^new_cobaltcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_cobaltcycle, name='new_cobaltcycle'),

    url(r'^edit_linaccycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_linaccycle, name='edit_linaccycle'),
    url(r'^new_linaccycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_linaccycle, name='new_linaccycle'),

    url(r'^edit_brachycycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_brachycycle, name='edit_brachycycle'),
    url(r'^new_brachycycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_brachycycle, name='new_brachycycle'),
    ####################
    # url(r'^import/$', importDiseaseCode.import_disease_code, name='import_disease_code')
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Doctor(models.Model):
    identity_fk = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.IntegerField()
    designation = models.CharField(max_length=100, blank=True)
    hospital = models.CharField(max_length=100, blank=True)

accounts/forms.py
from django import forms
# from django.contrib.auth import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import Doctor


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password'
        )


class EditDoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = (
            'mobile',
            'designation',
            'hospital'
        )

accounts/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

# Create your views here.
from accounts.forms import RegistrationForm, EditProfileForm, EditDoctorForm
from accounts.models import Doctor
from analytics.forms import SearchByNumForm, SearchByPkForm, SearchByDate


@login_required
def home(request):
    form = SearchByNumForm()
    form_pk = SearchByPkForm()
    form_date = SearchByDate()
    context = {'form': form, 'form_pk': form_pk, 'form_date': form_date}
    return render(request, 'accounts/home.html', context)


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)  # UserCreationForm
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = RegistrationForm()  #
        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)


@login_required
def profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('profile')
        else:
            return redirect('change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)


@login_required
def edit_doctorinfo(request):
    if not Doctor.objects.filter(identity_fk=request.user).exists():
        return new_doctorinfo(request)
    else:
        doctor = get_object_or_404(Doctor, identity_fk=request.user)
        if request.method == 'POST':
            form = EditDoctorForm(request.POST, instance=doctor)
            if form.is_valid():
                form.save()
                return redirect('view_doctorinfo')
        else:
            form = EditDoctorForm(instance=doctor)
            args = {'form': form}
            return render(request, 'accounts/edit_doctorinfo.html', args)


@login_required
def new_doctorinfo(request):
    if request.method == 'POST':
        form = EditDoctorForm(request.POST)  # UserCreationForm
        if form.is_valid():
            p_doctor = form.save(commit=False)
            p_doctor.identity_fk = request.user
            p_doctor.save()
            return redirect('view_doctorinfo')
    else:
        form = EditDoctorForm()  #
        args = {'form': form}
        return render(request, 'accounts/edit_doctorinfo.html', args)


@login_required
def view_doctorinfo(request):
    if not Doctor.objects.filter(identity_fk=request.user).exists():
        doctor = None
    else:
        doctor = get_object_or_404(Doctor, identity_fk=request.user)
    args = {'doctor': doctor}
    return render(request, 'accounts/view_doctorinfo.html', args)

accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	 <meta charset="UTF-8">
	<title>cDoctorAssistant</title>
	<link rel="icon" href="{% static 'img/favicon.ico' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/w3v4.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/webtable.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/w3template.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins"> <!--if any trouble, cmnt it out-->

	<!---->
	<meta http-equiv="x-ua-compatible" content="IE=Edge"/>
    <link rel="stylesheet" href="{% static 'css/autocomplete.css' %}">

	<link rel="stylesheet" href="{% static 'css/jquery.atwho.css' %}" />
    <link rel="stylesheet" href="{% static 'css/googleapistylesheet1.css' %}">
    <link rel="stylesheet" href="{% static 'css/googleapistylesheet2.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-2.2.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.caret.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.atwho.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/mobileview.js' %}"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--script type="text/javascript" src="{#% static 'js/InvestigationDataList.js' %}"></script-->
</head>
<!--head>
    <meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/w3v4.css' %}">
 <title>cDoctorAssistant</title>
</head-->
<body>
 <br>
      <div class="w3-top">
  <div class="w3-bar w3-white w3-wide w3-padding w3-card">
      {% if user.is_authenticated %}

    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="{% url 'home' %}" class="w3-bar-item w3-button">Home</a>
        <a href="{% url 'profile' %}" class="w3-bar-item w3-button"><b>{{user}}</b></a>
      <a href="{% url 'view_doctorinfo' %}" class="w3-bar-item w3-button">Doctor Info</a>
        <a href="{% url 'analytics:calculators' %}" class="w3-bar-item w3-button" target="_blank">Calculator</a>

      <a href="{% url 'change_password' %}" class="w3-bar-item w3-button">Change Password</a>
      <a href="{% url 'mylogout' %}" class="w3-bar-item w3-button">Log out</a>
    </div>
      {% else %}
        <div class="w3-right w3-hide-small">
        <a href="{% url 'mylogin' %}" class="w3-bar-item w3-button">Login</a>
        <a href="{% url 'register' %}" class="w3-bar-item w3-button">Register</a>
        <a href="{% url 'reset_password' %}" class="w3-bar-item w3-button">Forgot Password?</a>
      </div>
      {% endif %}
  </div>
</div>
 <br>
 <br>
<div class="w3-container">
{% block body %}
{% endblock %}
</div>
 <br><br>
<script type="text/javascript">
	 $(function(){
    $.fn.atwho.debug = true

    //var jeremy = decodeURI("J%C3%A9r%C3%A9my") // Jérémy
    var bangla = {{ bangla | safe }}
    var names = {{ medicine | safe }}
	var dose =  {{ dose | safe }} //["20 mg","50mg"]
	var timetable =  {{ timetable | safe }} // ["once daily","twice daily", "for 5 days"]

	var myarray = bangla.concat(names).concat(dose).concat(timetable);
	//myarray = myarray.concat(timetable);

	// var re =new RegExp('[a-z]+'); //;

    var at_config = {
      at:  "@", //  /\b(\w{2,})$/, //"@m",
      data: myarray,   //names,
      headerTpl: '<div class="atwho-header">Suggested Medicine List<small>↑&nbsp;↓&nbsp;</small></div>',
      insertTpl: '${name}',
      displayTpl: "<li>${name}</li>",
      limit: 200
    }
 var at_configt = {
      at: "!",  //"@t",
      data: timetable,
      headerTpl: '<div class="atwho-header">Time List<small>↑&nbsp;↓&nbsp;</small></div>',
      insertTpl: '${name}',
      displayTpl: "<li>${name}</li>",
      limit: 10
    }
    var at_configd = {
      at: "#",  //"@d",
      data: dose,
       headerTpl: '<div class="atwho-header">Dose List<small>↑&nbsp;↓&nbsp;</small></div>',
      displayTpl: "<li>${name}</li>",
      insertTpl: '${name}',
      limit: 10
    }
    $inputor = $('#inputor').atwho(at_configd).atwho(at_config).atwho(at_configt);
    $inputor.caret('pos', 47);
    $inputor.focus().atwho('run');

    $inputor0 = $('#inputor0').atwho(at_configd).atwho(at_config).atwho(at_configt);
    $inputor0.caret('pos', 47);
    $inputor0.focus().atwho('run');
  });

</script>
</body>
</html>

accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}

{% block body %}
<div class="w3-container">
    <div class="w3-display-middle w3-mobile">
        <h2>Change Password</h2>
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}

        <button type = "submit" style="color:#047ff8;">Submit</button>
        <button type="reset" value="Reset">Reset</button>
    </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/edit_doctorinfo.html
{% extends 'accounts/base.html' %}

{% block body %}
<div class="w3-container">
    <div class="w3-display-middle w3-mobile">
        <h2>Edit Doctor Information</h2>
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type = "submit" style="color:#047ff8;">Submit</button>
        <button type="reset" value="Reset">Reset</button>
    </form>
</div>
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'accounts/base.html' %}

{% block body %}
<div class="w3-container">
    <div class="w3-display-middle w3-mobile">
        <h2>Edit Profile</h2>
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type = "submit" style="color:#047ff8;">Submit</button>
        <button type="reset" value="Reset">Reset</button>
    </form>
</div>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block body %}
<div class="w3-container">
    <h2 align="center">Home</h2>

    <div class="w3-container w3-half">
           <p>
    <ul>
    <a href="{% url 'pbi:new_identity' %}" class="w3-btn w3-green">Create New Patient</a>
    </ul>
    </p>
        <br>
    <h3>Search by Mobile No:</h3>

    <form action="{% url 'analytics:form_handle' %}" method="POST" class="w3-text-black">
        {% csrf_token %}
    {{form.as_p}}
    <button type="submit" style="color:#047ff8;">Search</button>
    </form>

        <br>
        <h3>Search by ID:</h3>
    <form action="{% url 'analytics:form_handle_pk' %}" method="POST" class="w3-text-black">
        {% csrf_token %}
    {{form_pk.as_p}}
    <button type="submit" style="color:#047ff8;">Search</button>
    </form>
<br>
      
    </div>


    <div class="w3-container w3-half">
        <h3 align="center">Analytics</h3>
            <h3>Chemotherapy-wise Search:</h3>
    <a href="{% url 'analytics:sq_nact' %}" class="w3-btn w3-green">NACT</a> See patients in NACT Therapy<br><br>
    <a href="{% url 'analytics:sq_act' %}" class="w3-btn w3-green">ACT </a> See patients in ACT Therapy<br><br>
    <a href="{% url 'analytics:sq_concurrent' %}" class="w3-btn w3-green">Concurrent</a> See patients in Concurrent Therapy<br><br>
    <a href="{% url 'analytics:sq_palliative' %}" class="w3-btn w3-green">Palliative</a> See patients in Palliative Therapy<br><br>
<h3>Radiotherapy-wise Search:</h3>
<a href="{% url 'analytics:sq_linac' %}" class="w3-btn w3-green">Linac</a> See patients in Linac Therapy<br><br>
    <a href="{% url 'analytics:sq_cobalt' %}" class="w3-btn w3-green">Cobalt</a> See patients in Cobalt Therapy<br><br>
    <a href="{% url 'analytics:sq_brachy' %}" class="w3-btn w3-green">Brachy</a> See patients in Brachy Therapy<br><br>

    </div>



</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block body %}
<div class="w3-container">
    <div class="w3-display-middle w3-mobile">
        {% if user.is_authenticated %}
        <h2>You are already logged in!</h2>
        {% else %}
<h2>Welcome!</h2>
  <p>You can sign in here!</p>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type = "submit" style="color:#047ff8;">Sign In</button>
    <button type="reset" value="Reset">Reset</button>
    <br>
    <p><a href="{% url 'myadmin_login' %}">Login as admin</a></p>
</form>
        {% endif %}
    </div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block body %}
<div class="w3-container">

    <div class="w3-display-middle w3-mobile">
<h2>Good Bye!</h2>
  <p>You have logged out!</p>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/patientdetails_dummy.html
<div class="w3-main w3-light-gray" style="margin-left:340px;margin-right:40px">
    <div class="w3-container w3-white" style="margin-top:80px">
    <div><p><h2 align="center">Patient Info</h2></p></div>
    </div>
    {%include 'patientbasicinfo/ViewIdentity.html' %}
    <div class="w3-container">
        <div></div>
    </div>
    <!--*************************-->
    {%include 'patientbasicinfo/ViewProfile.html' %}
    {%include 'patientbasicinfo/ViewComorbidity.html' %}
    <div class="w3-container w3-white" style="margin-top:80px" id = "prescription">
       <ul><p>
        <h2 align="center">Prescriptions</h2>
    </p></ul>
    </div>
    {%include 'prescription/prescription.html' %}



    <div class="w3-container w3-white" style="margin-top:80px" id="treatmentplan">
    <p>
        <h2 align="center">Treatment Plan</h2>
    </p>
    </div>

    <div class="w3-container w3-white" style="margin-top:80px" id = "radiotherapy">
       <ul><p>
        <h2 align="center">Radio Therapy</h2>
    </p></ul>
    </div>
    {%include 'radiotherapy/Cobalt.html' %}
    {% if cobalt %}{% include 'table/cobalt_cycle.html' %} {% endif %}

    {%include 'radiotherapy/Linac.html' %}
    {% if linac %}{% include 'table/linac_cycle.html' %}{% endif %}

    {%include 'radiotherapy/Brachy.html' %}
    {% if brachy %}{% include 'table/brachy_cycle.html' %}{% endif %}

    <div class="w3-container w3-white" style="margin-top:80px" id = "chemotherapy">
       <ul><p>
        <h2 align="center">Chemo Therapy</h2>
    </p></ul>
    </div>
    {%include 'chemotherapy/NACT.html' %}
    {% if nact %}{% include 'table/nact_cycle.html' %}{% endif %}

    {%include 'chemotherapy/ACT.html' %}
    {% if act %}{% include 'table/act_cycle.html' %}{% endif %}

    {%include 'chemotherapy/concurrent.html' %}
    {% if concurrent %}{% include 'table/concurrent_cycle.html' %}{% endif %}

    {%include 'chemotherapy/palliative.html' %}
    {% if palliative %}{% include 'table/palliative_cycle.html' %}{% endif %}

    {%include 'surgeryhormone/surgery.html' %}
    {%include 'surgeryhormone/hormone.html' %}
<div class="w3-container w3-white" style="margin-top:80px" id = "targetedtherapy">
       <ul><p>
        <h2 align="center">Targeted Therapy</h2>
    </p></ul>
    </div>

    {%include 'targetedtherapy/TargetedTherapy.html' %}

    <div class="w3-container w3-white" style="margin-top:80px" id = "presentingfeatures">
       <ul><p>
        <h2 align="center">Presenting Features</h2>
    </p>
       </ul>
    </div>
    <div>
        <ul>
            <p>Here you can add new Status, Marker, Routines(CBC, RBS, LFT, KFT, Serum Electrolytes, Others) etc</p>
        </ul>
    </div>
    {%include 'status/status.html' %}
    {%include 'investigation/investigation.html' %}
    {%include 'imaging/imaging.html' %}
<div class="w3-container w3-white" style="margin-top:80px" id = "history">
       <ul><p>
        <h2 align="center">Patient History</h2>
    </p>
       </ul>
    </div>

    {%include 'history/history.html' %}
    {%include 'referralnote/ViewReferralNote.html' %}
    {%include 'followup/followup.html' %}

</div>

accounts/templates/accounts/reg_form.html
{% extends 'accounts/base.html' %}

{% block body %}
<div class="w3-container">
    <div class="w3-display-middle w3-mobile">
<br><br><h2>Registration</h2>
  <p>You can create new account here!</p>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type = "submit" style="color:#047ff8;">Register</button>
        <button type="reset" value="Reset">Reset</button>
</form>
    </div>
</div>

{% endblock %}