cDoctorAssistant/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static

from cDoctorAssistant import views

urlpatterns = [
                  url(r'^$', views.login_redirect, name='login_redirect'),
                  path('home/', include('patientbasicinfo.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('followup/', include('followup.urls')),
                  path('referralnotes/', include('referralnote.urls')),
                  path('history', include('history.urls')),
                  path('presentingfeatures/', include('presentingfeatures.urls')),
                  path('surgeryhormone', include('surgeryhormone.urls')),
                  url('radiotherapy/', include('radiotherapy.urls')),
                  url('chemotherapy/', include('chemotherapy.urls')),
                  url('targetedtherapy/', include('targetedtherapy.urls')),
                  url('tables/', include('tables.urls')),
                  url('analytics/', include('analytics.urls')),
                  url('pdfcreator/', include('pdfcreator.urls')),
                  path('admin/', admin.site.urls),
                  url('admin-login/$', admin.site.login, name='myadmin_login'),
                  url('^', include('django.contrib.auth.urls')),
                  url(r'^favicon.ico$',
                      RedirectView.as_view(  # the redirecting function
                          url=staticfiles_storage.url('img/favicon.ico'),
                          # converts the static directory + our favicon into a URL
                          # in my case, the result would be http://www.tumblingprogrammer.com/static/img/favicon.ico
                      ),
                      name="favicon"  # name of our view
                      ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdfcreator/urls.py
from django.conf.urls import url

from pdfcreator import views, summary

app_name = 'pdfcreator'

urlpatterns = [
    url(r'^view/prescription/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/(?P<user_pk>[0-9]+)/$', views.view_prescription, name='view_prescription'),
    url(r'^pdf/prescription/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/$', views.print_prescription, name='print_prescription'),
    #
    url(r'^view/referralnote/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/(?P<user_pk>[0-9]+)/$',
        views.view_referralnote, name='view_referralnote'),
    url(r'^pdf/referralnote/(?P<p_id>[0-9]+)/(?P<number>[0-9]+)/$', views.print_referralnote,
        name='print_referralnote'),
    #
    url(r'^view/report/(?P<user_pk>[0-9]+)/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', summary.view_report, name='view_report'),
    url(r'^pdf/report/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', summary.print_report, name='print_report'),

]

referralnote/urls.py
from django.conf.urls import url

from referralnote import views

app_name = 'referral_note'

#view_obj = views.ReferralNotes()

urlpatterns = [
    url(r'^(?P<p_id>[0-9]+)/delete_referralnote/(?P<notenum>[0-9]+)$', views.delete_refnote,
        name='delete_referralnote'),
    url(r'^(?P<p_id>[0-9]+)/edit_referralnote/(?P<notenum>[0-9]+)$', views.edit_referralnote, name='edit_referralnote'),
    url(r'^(?P<p_id>[0-9]+)/new_referralnote/$', views.new_referralnote, name='new_referralnote'),

]

tables/urls.py
from django.conf.urls import url

from tables import views, importDiseaseCode

app_name = 'table'

urlpatterns = [
    url(r'^edit_nactcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_nactcycle, name='edit_nactcycle'),
    url(r'^new_nactcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_nactcycle, name='new_nactcycle'),

    url(r'^edit_actcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_actcycle, name='edit_actcycle'),
    url(r'^new_actcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_actcycle, name='new_actcycle'),

    url(r'^edit_concurrcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_concurrcycle, name='edit_concurrcycle'),
    url(r'^new_concurrcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_concurrcycle, name='new_concurrcycle'),

    url(r'^edit_palliativecycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<cycleno>[0-9]+)$',
        views.edit_palliativecycle, name='edit_palliativecycle'),
    url(r'^new_palliativecycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$',
        views.new_palliativecycle, name='new_palliativecycle'),
    # ---------------------------------------------------------------------------------------
    url(r'^edit_cobaltcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_cobaltcycle, name='edit_cobaltcycle'),
    url(r'^new_cobaltcycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_cobaltcycle, name='new_cobaltcycle'),

    url(r'^edit_linaccycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_linaccycle, name='edit_linaccycle'),
    url(r'^new_linaccycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_linaccycle, name='new_linaccycle'),

    url(r'^edit_brachycycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/(?P<sino>[0-9]+)$',
            views.edit_brachycycle, name='edit_brachycycle'),
    url(r'^new_brachycycle/(?P<p_id>[0-9]+)/(?P<tp_num>[0-9]+)/$', views.new_brachycycle, name='new_brachycycle'),
    ####################
    # url(r'^import/$', importDiseaseCode.import_disease_code, name='import_disease_code')
]

referralnote/models.py
from django.db import models


# Create your models here.
from patientbasicinfo.models import Identity


class ReferralNote(models.Model):
    identity = models.ForeignKey(Identity, on_delete=models.CASCADE)
    purpose =  models.CharField(max_length=500, blank=True)
    condition = models.CharField(max_length=500,blank=True)
    refferedDept = models.CharField(max_length=200,blank=True)
    refferedConsultant = models.CharField(max_length=200,blank=True)
    responseNote = models.CharField(max_length=500,blank=True)
    remarks = models.CharField(max_length=500,blank=True)
    noteNo = models.IntegerField()

    def __str__(self):
        return self.identity.name

referralnote/forms.py
from django import forms

from referralnote.models import ReferralNote


class ReferralNoteForm(forms.ModelForm):
    class Meta:
        model = ReferralNote
        fields = (
            'purpose','condition', 'refferedDept', 'refferedConsultant', 'responseNote', 'remarks'
        )

referralnote/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
# from patientbasicinfo.controller import autocomplete
from patientbasicinfo.models import Identity
from referralnote.forms import ReferralNoteForm
from referralnote.models import ReferralNote


# class ReferralNotes:
@login_required
def delete_refnote(request, p_id, notenum):
    if not ReferralNote.objects.filter(identity=p_id).exists():
        raise Http404
    else:
        p = get_object_or_404(ReferralNote, identity=p_id, noteNo=notenum)
    p.delete()
    return redirect('view_patientdetails', p_id=p.identity.pk)


@login_required
def edit_referralnote(request, p_id, notenum):
    if not ReferralNote.objects.filter(identity=p_id).exists():
        return new_referralnote(request, p_id)
    else:
        p_referralnote = get_object_or_404(ReferralNote, identity=p_id, noteNo=notenum)
        if request.method == "POST":
            form = ReferralNoteForm(request.POST, instance=p_referralnote)
            if form.is_valid():
                p_referralnote = form.save()
                return redirect('view_patientdetails', p_id=p_referralnote.identity.pk)
        else:
            form = ReferralNoteForm(instance=p_referralnote)
            context = {'form': form, 'p_referralnote': p_referralnote}
        return render(request, 'referralnote/EditReferralNote.html', context)
        # return HttpResponse("Edit referralnote")


@login_required
def new_referralnote(request, p_id):
    num=1
    try:
        num = 1 + ReferralNote.objects.filter(identity=p_id).latest('noteNo').noteNo
    except:  # num = 1 + Investigations.objects.filter(identity_fk=p_id, type=data.type).count()
        print("Exception at upload handler referralnote/ReferralNote.py")
    if request.method == "POST":
        form = ReferralNoteForm(request.POST)
        if form.is_valid():
            p_referralnote = form.save(commit=False)
            p_referralnote.identity = Identity.objects.get(pk=p_id)
            p_referralnote.noteNo = num
            p_referralnote.save()
        return redirect('view_patientdetails', p_id=p_referralnote.identity.pk)
    else:
        form = ReferralNoteForm()
        context = {'form': form}
    return render(request, 'referralnote/EditReferralNote.html', context)
    # return HttpResponse("new referralnote")

referralnote/templates/referralnote/EditReferralNote.html
{% extends 'accounts/base.html' %}
{% block body %}
<div class="w3-display-middle w3-mobile">
<ul>
<h3>Referral Note #{{p_referralnote.noteNo}}</h3>
    <form method = post>
        {% csrf_token %}
        <!--{#{ form.as_p }}-->
<p><label for="id_purpose">Purpose:</label> <input type="text" name="purpose" value="{{p_referralnote.purpose}}" maxlength="500" id="id_purpose" /></p>
<p><label for="id_condition">Condition:</label> <input type="text" name="condition" value="{{ p_referralnote.condition}}" maxlength="500" id="id_condition" /></p>
<p><label for="id_refferedDept">Referred Dept:</label> <input type="text" name="refferedDept" value="{{ p_referralnote.refferedDept}}" maxlength="200" id="id_refferedDept" /></p>
<p><label for="id_refferedConsultant">Referred Consultant:</label> <input type="text" name="refferedConsultant" value="{{ p_referralnote.refferedConsultant}}" maxlength="200" id="id_refferedConsultant" /></p>
<p><label for="id_responseNote">Response Note:</label> <input type="text" name="responseNote" value="{{ p_referralnote.responseNote}}" maxlength="500"id="id_responseNote" /></p>
<p><label for="id_remarks">Remarks:</label> <input type="text" name="remarks" value="{{ p_referralnote.remarks}}" maxlength="500" id="id_remarks" /></p>
        <button type = "submit" style="color:#047ff8;">Submit</button>
        <button type="reset" value="Reset">Reset</button>
    </form>
</ul>
</div>
{% endblock %}

referralnote/templates/referralnote/ViewReferralNote.html
<div class="w3-container" style="margin-top:20px" id="referralnote">
{% if referralnote %}
<div class="w3-container w3-white" style="margin-top:20px">
    <ul>
        <h2 align="center">Referral Note</h2>
    </ul>
</div>

    {% for i in referralnote %}
    <div class="w3-row-padding">
        <ul>
            <div class="w3-half w3-margin-bottom">
                <ul class="w3-ul w3-light-grey w3-center">
                    <li class="w3-black w3-large w3-padding-16">Referral Note #</li>
                    <li class="w3-padding-16">Purpose</li>
                    <li class="w3-padding-16">Condition</li>
                    <li class="w3-padding-16">Referred Department</li>
                    <li class="w3-padding-16">Referred Consultant</li>
                    <li class="w3-padding-16">Response Note</li>
                    <li class="w3-padding-16">Remarks</li>

                </ul>
            </div>
        </ul>
        <ul>
            <div class="w3-half">
                <ul class="w3-ul w3-light-grey w3-center">
                    <li class="w3-black w3-large w3-padding-16">{{i.noteNo}}</li>
                    <li class="w3-padding-16">- {{i.purpose}}</li>
                    <li class="w3-padding-16">- {{i.condition}}</li>
                    <li class="w3-padding-16">- {{i.refferedDept}}</li>
                    <li class="w3-padding-16">- {{i.refferedConsultant}}</li>
                    <li class="w3-padding-16">- {{i.responseNote}}</li>
                    <li class="w3-padding-16">- {{i.remarks}}</li>
                </ul>
            </div>
        </ul>
        </div>
    <ul>
        <p>
            <a href="{% url 'referral_note:edit_referralnote' i.identity.pk i.noteNo %}" class="w3-btn w3-green">Edit</a>
            <a href="{% url 'pdfcreator:view_referralnote' i.identity.pk i.noteNo user.pk %}" class="w3-btn w3-blue">Print</a>
            <a href="{% url 'referral_note:delete_referralnote' i.identity.pk i.noteNo %}" class="w3-btn w3-red w3-right"
            onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
        </p>
        <br>
    </ul><br>
    {% endfor %}


    <div>
        <ul>
    <a href="{% url 'referral_note:new_referralnote' patient.pk %}" class="w3-btn w3-green">Add New</a>
    </ul>
    </div>
{% else %}
    <div>
        <ul>
            <h3>Nothing in referral notes.</h3>
            <a href="{% url 'referral_note:new_referralnote' patient.pk %}" class="w3-btn w3-green">Add New</a>
        </ul>
    </div>
{% endif %}
</div>